### ISSUE TITLE
`<cluster_name>-token` Secret has disappeared during a CP node scale out operation

### ISSUE THREAD

**Issue by marcdavoli** [cluster-api-provider-k3s/cluster-api-k3s#53]
During a control-plane node scale out operation, it seems the `<cluster_name>-token` Secret has been deleted. I haven't figured out why or by whom yet.

> Note: This is in AWS, with CAPA.

- Current configuration: 3 CP nodes, instance type: t3.large
- Desired configuration: 3 CP nodes, instance type: t3.medium

This was done by creating a new `AWSMachineTemplate` and making the `KThreesControlPlane` to use it by specifying its name in `.spec.infrastructureTemplate.name`:
```yaml
kubectl get kthreescontrolplanes.controlplane.cluster.x-k8s.io mycluster-control-plane -o yaml | yq .spec
infrastructureTemplate:
  apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
  kind: AWSMachineTemplate
  name: mycluster-control-plane-small
```
The operation started by successfully adding a 4th node to the cluster (t3.medium), then stopped altogether.

The cluster's CP etcd seems to still be consistent and reachable, no issues there.

But after investigating I found these errors in the `capi-k3s-bootstrap-controller-manager`:

```capi-k3s-bootstrap-controller-manager-55585c647d-cnkh7 manager 1.6953206655230973e+09	ERROR	Reconciler error	{"controller": "kthreesconfig", "controllerGroup": "bootstrap.cluster.x-k8s.io", "controllerKind": "KThreesConfig", "kThreesConfig": {"name":"mycluster-control-plane-5grmd","namespace":"mynamespace"}, "namespace": "mynamespace", "name": "mycluster-control-plane-5grmd", "reconcileID": "abe6975a-f740-4a3f-88fa-3d4824d867a8", "error": "failed to get token for KThreesConfig mynamespace/mycluster-control-plane-5grmd: Secret \"mycluster-token\" not found", "errorVerbose": "Secret \"mycluster-token\" not found\nfailed to get token for KThreesConfig mynamespace/mycluster-control-plane-5grmd\ngithub.com/cluster-api-provider-k3s/cluster-api-k3s/bootstrap/controllers.(*KThreesConfigReconciler).retrieveToken\n\tgithub.com/cluster-api-provider-k3s/cluster-api-k3s/bootstrap/controllers/kthreesconfig_controller.go:540\ngithub.com/cluster-api-provider-k3s/cluster-api-k3s/bootstrap/controllers.(*KThreesConfigReconciler).joinControlplane\n\tgithub.com/cluster-api-provider-k3s/cluster-api-k3s/bootstrap/controllers/kthreesconfig_controller.go:227\ngithub.com/cluster-api-provider-k3s/cluster-api-k3s/bootstrap/controllers.(*KThreesConfigReconciler).Reconcile\n\tgithub.com/cluster-api-provider-k3s/cluster-api-k3s/bootstrap/controllers/kthreesconfig_controller.go:207\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234\nruntime.goexit\n\truntime/asm_amd64.s:1598"}```

So I went to take a look at the secret, which does in fact not exist anymore. I have other clusters that have not gone through the same CP node scale out operation that still have the equivalent secret, but this one doesn't anymore

```
$ kubectl get secret -n anothernamespace | grep anothercluster-token
  anothercluster-token ...
$ kubectl get secret -n mynamespace | grep mycluster-token
$ 
```

Looking at the `KThreesControlPlane`'S status: 
```yaml
k get kthreescontrolplanes.controlplane.cluster.x-k8s.io mycluster-control-plane -o yaml | yq .status
conditions:
  - lastTransitionTime: "2023-09-21T18:18:41Z"
    message: Rolling 1 replicas with outdated spec (2 replicas up to date)
    reason: RollingUpdateInProgress
    severity: Warning
    status: "False"
    type: Ready
  - lastTransitionTime: "2023-09-21T15:57:57Z"
    status: "True"
    type: Available
  - lastTransitionTime: "2023-09-21T15:56:51Z"
    status: "True"
    type: CertificatesAvailable
  - lastTransitionTime: "2023-09-21T17:16:59Z"
    status: "True"
    type: ControlPlaneComponentsHealthy
  - lastTransitionTime: "2023-09-21T17:17:00Z"
    message: 0 of 2 completed
    reason: DataSecretGenerationFailed @ Machine/mycluster-control-plane-cd2w4
    severity: Warning
    status: "False"
    type: MachinesReady
  - lastTransitionTime: "2023-09-21T18:18:41Z"
    message: Rolling 1 replicas with outdated spec (2 replicas up to date)
    reason: RollingUpdateInProgress
    severity: Warning
    status: "False"
    type: MachinesSpecUpToDate
  - lastTransitionTime: "2023-09-21T17:39:57Z"
    message: Scaling down control plane to 1 replicas (actual 3)
    reason: ScalingDown
    severity: Warning
    status: "False"
    type: Resized
initialized: true
observedGeneration: 1
ready: true
readyReplicas: 2
replicas: 3
selector: cluster.x-k8s.io/cluster-name=mycluster,cluster.x-k8s.io/control-plane
unavailableReplicas: 1
updatedReplicas: 2
```

That same error message DataSecretGenerationFailed @ Machine/mycluster-control-plane-cd2w4 also shows when using `clusterctl describe cluster mycluster --show-conditions all`.

I saw some code [here ](https://github.com/cluster-api-provider-k3s/cluster-api-k3s/blob/d95461fc75da55450b6cb45c31243e8b5dc018af/bootstrap/controllers/kthreesconfig_controller.go#L427C18-L427C39)for generating a token, I thought it may be possible to somehow force the cluster to redo the 'initialization' step, but that didn't work out.

Is there anything that can be done to force the recreation of the secret and break free of this weird status the cluster is in?

Thanks
