### ISSUE TITLE
Missing metadata.yaml in release

### ISSUE THREAD

**Issue by anmazzotti** [cluster-api-provider-k3s/cluster-api-k3s#55]
Hello, I have issues running `clusterctl` with the current release scheme.
The `metadata.yaml` is not published, so it's not possible to use `clusterctl init` to install this provider.

My config is the following:

```yaml
providers:
- name: "k3s"
  url: "https://github.com/cluster-api-provider-k3s/cluster-api-k3s/releases/v0.1.7/bootstrap-components.yaml"
  type: "BootstrapProvider"
- name: "k3s"
  url: "https://github.com/cluster-api-provider-k3s/cluster-api-k3s/releases/v0.1.7/control-plane-components.yaml"
  type: "ControlPlaneProvider"
```

Running `clusterctl init` returns the following error:

```bash
$clusterctl init --bootstrap k3s --control-plane k3s
Fetching providers
Error: failed to read "metadata.yaml" from the repository for provider "bootstrap-k3s": failed to download files from GitHub release v0.1.7: failed to get file "metadata.yaml" from "v0.1.7" release
```

For the moment a workaround would be to apply the manifests manually and avoid `clusterctl`: 

```bash
kubectl apply -f https://github.com/cluster-api-provider-k3s/cluster-api-k3s/releases/download/v0.1.7/bootstrap-components.yaml
kubectl apply -f https://github.com/cluster-api-provider-k3s/cluster-api-k3s/releases/download/v0.1.7/control-plane-components.yaml
```
