### ISSUE TITLE
💡How to access ETCD from mgmt cluster?

### ISSUE THREAD

**Issue by mogliang** [cluster-api-provider-k3s/cluster-api-k3s#75]
k3s etcd is not a static pod but inside [k3s host process](https://docs.k3s.io/architecture). Which means we cannot use kubernetes port-forward to access k3s endpoint. I want to start this thread to discuss how we can access k3s etcd endpoint from capi mgmt cluster.

Below are some ideas in my mind:

1. Access etcd endpoint directly by vm address.

This is the most straightforward way. capi machine has `MachineAddresses` field which expose vm address info, mgmt cluster can start a connection to machine address on 2379 port to access etcd client endpoints.

The big drawback could be: it has stricter network requirement, it requires network be routable between mgmt cluster and target cluster vm. Besides, it could expose more attack surface, that means users may require more effort to ensure the system security. 

2. Daemonset in target cluster cp nodes to forward etcd traffic.

We deploy daemonset to target cluster's cp nodes, it does one simple job, just forward 2379 traffic to its host's 2379 port. So, mgmt cluster can still use kubernetes port-forward to access daemonset pod, and forward again to host etcd endpoint. Theoretically, this shall work, but I haven't tested yet.

The drawback is also very obvious, it need deploy pods on target cluster, which is not very user-friendly.

Although k3s cp provider can still work without access etcd, but it's not safe, we need fix this issue to make project production ready. Please comment below to share your idea⚡

**Comment by mogliang** [comment]
cc @zawachte

**Comment by mogliang** [comment]
The doc says we can use apiserver as proxy to access node!? Any one has more details on this?
https://kubernetes.io/docs/concepts/cluster-administration/proxies/

The [apiserver proxy](https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster-services/#discovering-builtin-services):

is a bastion built into the apiserver
connects a user outside of the cluster to cluster IPs which otherwise might not be reachable
runs in the apiserver processes
client to proxy uses HTTPS (or http if apiserver so configured)
proxy to target may use HTTP or HTTPS as chosen by proxy using available information
can be used to reach a **Node**, Pod, or Service
does load balancing when used to reach a Service

**Comment by lukebond** [comment]
i'm not familiar with the apiserver proxy, so can't shed any light on it. docs are quite thin, they mention it can be used to access nodes but don't show you how. `kubectl cluster-info` seems to list only the services in the `kube-system` namespace on one of our clusters here that i'm looking at. i think using services isn't useful without adding a daemonset like you propose. would be interested to know how the node access works if anyone knows. going in via the k8s API is attractive as it doesn't require extra networking configuration.for option 1 to work for us we'd need to add `2379` to the CP security group. easy enough to do, but an added burden for users of MHS that might not be obvious.

**Comment by zawachte** [comment]
I think we should be able to manually create a endpoint resource and service resource which should allow us to do the same tunneling (port-forward) that kubeadm provider does.

This is similar to how prom-operator sets up prom to scrape kubelet/cadvisor metrics.

**Comment by lukebond** [comment]
ah so something like this?

- create an `Endpoints` resource, with a subset entry for each CP host, and a port entry for `2379`, defined in the kube-system namespace
- use the api proxy linked above ([here](https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster-services/#discovering-builtin-services)) to access it

given you can point endpoints subsets to nodes, this might be what the docs meant when they say you can use api proxies to communicate with nodes. well you can, indirectly, via a service, if you create one by hand like that. seems a bit unclear of the docs if that's what they meant!

**Comment by mogliang** [comment]
tested the solution (service+endpoints) zawachte provided on my k3s enviornment. Yes, pod was able to access host etcd by accessing the service, However, this service is not allowed for port-forward. port foward will give err below:
``` error: cannot attach to *v1.Service: invalid service 'etcd-service': Service is defined without a selector ```

searched a bit, and someone gave a solution https://stackoverflow.com/questions/56870808/access-external-database-resource-wrapped-in-service-without-selector . That means we still need to create a proxy pod anyway.

**Comment by mogliang** [comment]
tested deploying pod as etcd proxy and use port-forwarding to connect, works! the proxy yaml are as below
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: etcd-proxy
  namespace: kube-system
  labels:
    app: etcd-proxy
spec:
  selector:
    matchLabels:
      name: etcd-proxy
  template:
    metadata:
      labels:
        name: etcd-proxy
    spec:
      nodeSelector:
        node-role.kubernetes.io/etcd: "true"
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: etcd-proxy
        image: alpine/socat
        env:
        - name: HOSTIP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        args: 
        - TCP4-LISTEN:2380,fork,reuseaddr
        - TCP4:$(HOSTIP):2380
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log

```
We can let k3s bootstrap provider to install this daemonset.

Guys, what do you think? if looks good, i will proceed to work on a pr.
