### ISSUE TITLE
Cannot get rid of `disable-cloud-controller: true` in k3s config

### ISSUE THREAD

**Issue by mquhuy** [cluster-api-provider-k3s/cluster-api-k3s#89]
Hello, still me, the guy in #87 who is trying to make CABP3 work with Metal3.

I'm bumping into a situation in which no matter how I tried, I seem cannot get rid of the `disable-cloud-controller: true` in the `/etc/rancher/k3s/config.yaml`. This error makes the node tainted with label `node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule` and can't be scheduled into. I found [this thread](https://github.com/k3s-io/k3s/discussions/6329) in `k3s` community which seems to describe my issue perfectly. (I'm pretty sure that is the main issue, as I could remove the taint by log in to the node, remove that line manually and restart k3s service)

I found that in https://github.com/cluster-api-provider-k3s/cluster-api-k3s/blob/main/pkg/k3s/config.go#L45, this field seems to be negative of `serverConfig.disableExternalCloudProvider`, so in my template, I specifically set it to `true`:

```yaml
serverConfig:
    disableExternalCloudProvider: true
```
(This field is, btw, missing from https://github.com/cluster-api-provider-k3s/cluster-api-k3s/blob/main/samples/deployment/control-plane-k3s/v1.2.2/control-plane-components.yaml and https://github.com/cluster-api-provider-k3s/cluster-api-k3s/blob/main/samples/deployment/bootstrap-k3s/v1.2.2/bootstrap-components.yaml, so I did have to edit those files and put the local changes to `clusterctl` config).

However, despite this new field was accepted and displayed correctly when I describe my `kthreescontrolplane` object, the `disable-cloud-controller: true` still managed to end up in the node's k3s config. Could you please help me with this? Maybe there's something I should have/have not done? Thank you a lot in advance!

**Comment by mogliang** [comment]
disableExternalCloudProvider: true is the right setting. Below is our cr to enable builtin cloudprovider.

```
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KThreesControlPlane
metadata:
  name: ${CLUSTER_NAME}-control-plane
spec:
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AksInfraMachineTemplate
    name: ${CLUSTER_NAME}-control-plane
  kthreesConfigSpec:
    serverConfig:
      disableExternalCloudProvider: true
  replicas: ${CONTROL_PLANE_MACHINE_COUNT}
  version: ${KUBERNETES_VERSION}
```

can you verify your k3s controlplane yaml ?
